### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by groenroos** [HaaLeo/vscode-stylint#9]
| VS Code Version | vscode-stylint Version | Installed Stylint Version | OS |
| --------------- | ---------------------- | ------------------------- | -- |
|  1.39.2               | 0.1.3                       |   2.0.0                        |  macOS Catalina 10.15  |

# Description
Each time the Stylint check is triggered (e.g. keystroke), a notification is triggered with **"Stylint: Unexpected end of JSON input. Please see the 'Stylint' output channel for details."**

Attempted to restart VSCode, attempted various settings in `settings.json` including different working directories and stylintrc locations, attempted different chmod settings for `.stylintrc`. 

Contents of `.stylintrc` in the project root is valid and complete JSON.

## Expected Behavior
Notification should not occur. Stylint check should run.

## Actual Behavior
Notification occurs. Stylint does not run.

# Steps to Reproduce
I installed Visual Code Studio, and the plug-in onto a brand new Mac.

# Logs

Filename at `textDocument.uri` and actual Stylus input at `contentChanges.text` redacted in the logs below.
<details>
<pre><code>
[Trace - 12:50:08 AM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///Users/groenroos/Repositories/(...).styl",
        "version": 8
    },
    "contentChanges": [
        {
            "text": "(big block of Stylus here)"
        }
    ]
}

[Trace - 12:50:08 AM] Received request 'window/showMessageRequest - (30)'.
Params: {
    "type": 1,
    "message": "Stylint: Unexpected end of JSON input. Please see the 'Stylint' output channel for details.",
    "actions": []
}

[Trace - 12:50:08 AM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "Stylint stack trace:"
}

[Error - 12:50:08 AM] Stylint stack trace:
[Trace - 12:50:08 AM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at StylintModule.<anonymous> (/Users/groenroos/.vscode/extensions/haaleo.vscode-stylint-0.1.3/server/out/stylintModule.js:44:25)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/groenroos/.vscode/extensions/haaleo.vscode-stylint-0.1.3/server/out/stylintModule.js:8:58)"
}

[Error - 12:50:08 AM] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StylintModule.<anonymous> (/Users/groenroos/.vscode/extensions/haaleo.vscode-stylint-0.1.3/server/out/stylintModule.js:44:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/groenroos/.vscode/extensions/haaleo.vscode-stylint-0.1.3/server/out/stylintModule.js:8:58)
[Trace - 12:50:08 AM] Received notification 'stylint/status'.
Params: {
    "state": 3
}
</code></pre></details>

# Settings
<details><pre><code>
{
    "stylint.stylintrcPath": ".stylintrc",
    "stylint.trace.server": "verbose",
    "files.associations": {
        "*.vue": "stylus"
    }
}
</code></pre></details>

**Comment by groenroos** [comment]
Exactly as #4, this seems to be related to having too many errors and warnings. If `maxErrors` and `maxWarnings` in `.stylintrc` are both set to `10`, the problem goes away, and Stylint runs normally.

When running Stylint outside of VSCode directly with the CLI tool, this project returns 4,686 warnings and 0 errors (this is easy to achieve in any mid-to-large size project, when the `sortOrder` option is edited).

**Comment by HaaLeo** [comment]
Hi @groenroos thank you for your contribution. Seems like there is a problem when [parsing the output](https://github.com/HaaLeo/vscode-stylint/blob/master/server/src/stylintModule.ts#L49) of the [stylint json reporter](https://github.com/sertae/stylint-json-reporter).  
Can you please provide a `example.styl` file as well as your `.stylintrc` file so I can try to reproduce this error?

**Comment by groenroos** [comment]
Sure, here's a repo with an `example.styl` (filled with random Stylus code from groenroos/bulma-stylus#7), my `.stylintrc` and the `.vscode` configuration:

https://github.com/groenroos/stylint-error-test

The error message is reproducible on two different laptops of mine.

If you save the `example.styl` file to make Stylint run (as I prefer to run Stylint on save), it will throw the **"Stylint: Unexpected end of JSON input. Please see the 'Stylint' output channel for details."** error.

However, Stylint will run without errors and display all linting warnings if any one of the following is done:

- `sortOrder` in `.stylintrc` is changed to `never` - thus reducing the number of linting warnings produced
- `maxErrors` and `maxWarnings` in `.stylintrc` are set to `10` - thus capping the number of linting warnings
- The entire `.textarea` block starting from line 368 in `example.styl` is removed - thus reducing the number of linting warnings by reducing the number of lines linted
- Stylint is run independently of VSCode on the OS command line (produces 83 linting warnings if no other above changes are made)

Thus it seems like it is very much related to the number of linting warnings produced, and is specific to this VSCode extension.

It does not seem to be related to number of lines linted, as longer files can be linted just fine if the number of resulting linting warnings is reduced by other means.

The highest number of warnings I could make this extension produce was 77 in this instance, by removing the `.textarea` declaration block. Even reducing the `.textarea` declaration to just a single line will still trigger the error.

I hope this is helpful in fixing the bug! :)

**Comment by HaaLeo** [comment]
@groenroos thank you very much for the additional information as well as the test repo 👍. Unfortunately I can only test with windows. Debugging the extension under _windows 10_ I do not get the described error even with the test repo.  Therefore maybe it's a macOS related problem.
Another possible cause could be that [`sb-exec` runs out of memory](https://github.com/steelbrain/exec/issues/100#issuecomment-477326032) which could be the reason why I cannot reproduce it.  

Anyway, to check whether this is related to the `stylint-json-reporter`, please replace the test repository's `package.json` with:
```json
{
  "devDependencies": {
    "stylint": "^2.0.0",
    "stylint-json-reporter": "^0.3.1"
  },
  "scripts": {
    "stylint": "stylint",
    "stylintjson": "stylint --reporter stylint-json-reporter"
  }
}
```

and then run 
```shell
npm i
npm run stylintjson
```

**Comment by groenroos** [comment]
@HaaLeo Thanks for the quick reply!

I've done as you suggested and it seems to spit out the JSON for the errors just fine:

<details>
<pre><code>
stylint-test groenroos$ npm run stylintjson

> @ stylintjson /Users/oskari/Repositories/stylint-test
> stylint --reporter stylint-json-reporter

[{"filePath":"example.styl","messages":[{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":49},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":50},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":51},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":52},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":53},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":54},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":55},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":59},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":60},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":61},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":69},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":72},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":75},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":78},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":97},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":98},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":99},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":113},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":114},{"severity":"Warning","message":"preferred quote style is double quotes","rule":"quotePref","line":116,"column":0},{"severity":"Warning","message":"preferred quote style is double quotes","rule":"quotePref","line":117,"column":0},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":120},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":121},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":125},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":126},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":136},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":137},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":139},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":141},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":142},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":152},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":153},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":154},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":160},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":161},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":167},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":168},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":181},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":182},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":183},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":186},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":187},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":204},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":205},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":206},{"severity":"Warning","message":"preferred quote style is double quotes","rule":"quotePref","line":209,"column":0},{"severity":"Warning","message":"preferred quote style is double quotes","rule":"quotePref","line":210,"column":0},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":217},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":218},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":222},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":223},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":235},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":237},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":238},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":239},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":250},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":251},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":252},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":253},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":256},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":257},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":261},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":262},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":286},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":289},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":290},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":312},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":318},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":326},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":327},{"severity":"Warning","message":"preferred quote style is double quotes","rule":"quotePref","line":332,"column":0},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":359},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":360},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":363},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":364},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":365},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":366},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":370},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":371},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":372},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":373},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":374},{"severity":"Warning","message":"prefer grouped when sorting properties","rule":"sortOrder","line":377}],"errorCount":0,"warningCount":83}]
</code></pre>
</details>

But then just running `stylint` as-is also works:

<details>
<pre><code>
stylint-test groenroos$ npm run stylint

> @ stylint /Users/oskari/Repositories/stylint-test
> stylint

./example.styl
49      warning  prefer grouped when sorting properties  sortOrder         
50      warning  prefer grouped when sorting properties  sortOrder         
51      warning  prefer grouped when sorting properties  sortOrder         
52      warning  prefer grouped when sorting properties  sortOrder         
53      warning  prefer grouped when sorting properties  sortOrder         
54      warning  prefer grouped when sorting properties  sortOrder         
55      warning  prefer grouped when sorting properties  sortOrder         
59      warning  prefer grouped when sorting properties  sortOrder         
60      warning  prefer grouped when sorting properties  sortOrder         
61      warning  prefer grouped when sorting properties  sortOrder         
69      warning  prefer grouped when sorting properties  sortOrder         
72      warning  prefer grouped when sorting properties  sortOrder         
75      warning  prefer grouped when sorting properties  sortOrder         
78      warning  prefer grouped when sorting properties  sortOrder         
97      warning  prefer grouped when sorting properties  sortOrder         
98      warning  prefer grouped when sorting properties  sortOrder         
99      warning  prefer grouped when sorting properties  sortOrder         
113     warning  prefer grouped when sorting properties  sortOrder         
114     warning  prefer grouped when sorting properties  sortOrder         
116     warning  preferred quote style is double quotes  quotePref         
117     warning  preferred quote style is double quotes  quotePref         
120     warning  prefer grouped when sorting properties  sortOrder         
121     warning  prefer grouped when sorting properties  sortOrder         
125     warning  prefer grouped when sorting properties  sortOrder         
126     warning  prefer grouped when sorting properties  sortOrder         
136     warning  prefer grouped when sorting properties  sortOrder         
137     warning  prefer grouped when sorting properties  sortOrder         
139     warning  prefer grouped when sorting properties  sortOrder         
141     warning  prefer grouped when sorting properties  sortOrder         
142     warning  prefer grouped when sorting properties  sortOrder         
152     warning  prefer grouped when sorting properties  sortOrder         
153     warning  prefer grouped when sorting properties  sortOrder         
154     warning  prefer grouped when sorting properties  sortOrder         
160     warning  prefer grouped when sorting properties  sortOrder         
161     warning  prefer grouped when sorting properties  sortOrder         
167     warning  prefer grouped when sorting properties  sortOrder         
168     warning  prefer grouped when sorting properties  sortOrder         
181     warning  prefer grouped when sorting properties  sortOrder         
182     warning  prefer grouped when sorting properties  sortOrder         
183     warning  prefer grouped when sorting properties  sortOrder         
186     warning  prefer grouped when sorting properties  sortOrder         
187     warning  prefer grouped when sorting properties  sortOrder         
204     warning  prefer grouped when sorting properties  sortOrder         
205     warning  prefer grouped when sorting properties  sortOrder         
206     warning  prefer grouped when sorting properties  sortOrder         
209     warning  preferred quote style is double quotes  quotePref         
210     warning  preferred quote style is double quotes  quotePref         
217     warning  prefer grouped when sorting properties  sortOrder         
218     warning  prefer grouped when sorting properties  sortOrder         
222     warning  prefer grouped when sorting properties  sortOrder         
223     warning  prefer grouped when sorting properties  sortOrder         
235     warning  prefer grouped when sorting properties  sortOrder         
237     warning  prefer grouped when sorting properties  sortOrder         
238     warning  prefer grouped when sorting properties  sortOrder         
239     warning  prefer grouped when sorting properties  sortOrder         
250     warning  prefer grouped when sorting properties  sortOrder         
251     warning  prefer grouped when sorting properties  sortOrder         
252     warning  prefer grouped when sorting properties  sortOrder         
253     warning  prefer grouped when sorting properties  sortOrder         
256     warning  prefer grouped when sorting properties  sortOrder         
257     warning  prefer grouped when sorting properties  sortOrder         
261     warning  prefer grouped when sorting properties  sortOrder         
262     warning  prefer grouped when sorting properties  sortOrder         
286     warning  prefer grouped when sorting properties  sortOrder         
289     warning  prefer grouped when sorting properties  sortOrder         
290     warning  prefer grouped when sorting properties  sortOrder         
312     warning  prefer grouped when sorting properties  sortOrder         
318     warning  prefer grouped when sorting properties  sortOrder         
326     warning  prefer grouped when sorting properties  sortOrder         
327     warning  prefer grouped when sorting properties  sortOrder         
332     warning  preferred quote style is double quotes  quotePref         
359     warning  prefer grouped when sorting properties  sortOrder         
360     warning  prefer grouped when sorting properties  sortOrder         
363     warning  prefer grouped when sorting properties  sortOrder         
364     warning  prefer grouped when sorting properties  sortOrder         
365     warning  prefer grouped when sorting properties  sortOrder         
366     warning  prefer grouped when sorting properties  sortOrder         
370     warning  prefer grouped when sorting properties  sortOrder         
371     warning  prefer grouped when sorting properties  sortOrder         
372     warning  prefer grouped when sorting properties  sortOrder         
373     warning  prefer grouped when sorting properties  sortOrder         
374     warning  prefer grouped when sorting properties  sortOrder         
377     warning  prefer grouped when sorting properties  sortOrder         

Stylint: 0 Errors.
Stylint: 83 Warnings.
</code></pre>
</details>

The problem must be somewhere else!

**Comment by HaaLeo** [comment]
I changed the implementation to use [`promisify-child-process`](https://github.com/jcoreio/promisify-child-process) with `maxBuffer=1024*1024` instead of `sb-exec`. 
@groenroos could you give it a try by downloading and unpacking the archive [vscode-stylint-0.1.4-dev1.zip](https://github.com/HaaLeo/vscode-stylint/files/3809843/vscode-stylint-0.1.4-dev1.zip)?

Then run `code --install-extension vscode-stylint-0.1.4-dev1.vsix` to install it.

**Comment by groenroos** [comment]
Thanks for the update! I did the following:

- Downloaded and unpacked the zip file you linked
- Uninstalled the currently installed version of the `vscode-stylint` plugin
- Ran `code --install-extension vscode-stylint-0.1.4-dev1.vsix`
- `Cmd-Shift-P` and `Reload Window` to make the plugin appear

However, the same error still persists with the same parameters as above. I even fully restarted VSCode, and it still occurs exactly as before.

Here's the full error with `"stylint.trace.server": "verbose"`:

<details>
<pre><code>
[Trace - 4:25:32 PM] Sending request 'textDocument/willSaveWaitUntil - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/oskari/Repositories/stylint-test/example.styl"
    },
    "reason": 1
}


[Trace - 4:25:32 PM] Received response 'textDocument/willSaveWaitUntil - (1)' in 1ms.
Result: []


[Trace - 4:25:32 PM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///Users/oskari/Repositories/stylint-test/example.styl",
        "version": 1
    }
}


[Trace - 4:25:32 PM] Received request 'window/showMessageRequest - (6)'.
Params: {
    "type": 1,
    "message": "Stylint: Unexpected end of JSON input. Please see the 'Stylint' output channel for details.",
    "actions": []
}


[Trace - 4:25:32 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "Stylint stack trace:"
}


[Error - 4:25:32 PM] Stylint stack trace:
[Trace - 4:25:32 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at StylintModule.<anonymous> (/Users/oskari/.vscode/extensions/haaleo.vscode-stylint-0.1.4-dev1/server/out/stylintModule.js:54:25)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/oskari/.vscode/extensions/haaleo.vscode-stylint-0.1.4-dev1/server/out/stylintModule.js:8:58)"
}


[Error - 4:25:32 PM] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StylintModule.<anonymous> (/Users/oskari/.vscode/extensions/haaleo.vscode-stylint-0.1.4-dev1/server/out/stylintModule.js:54:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/oskari/.vscode/extensions/haaleo.vscode-stylint-0.1.4-dev1/server/out/stylintModule.js:8:58)
[Trace - 4:25:32 PM] Received notification 'stylint/status'.
Params: {
    "state": 3
}


[Trace - 4:25:32 PM] Sending response 'window/showMessageRequest - (5)'. Processing request took 11540ms
No result returned.
</pre></code>
</details>

**Comment by HaaLeo** [comment]
Thanks for testing it. 
However then I have no clue what could be the cause of this issue without being able to reproduce it. 
I am glad to accept a PR on this from somebody who can reproduce it.

**Comment by groenroos** [comment]
I would be happy to lend a hand, but unfortunately I don't know the first thing about developing VSCode extensions.

It'd be interesting to see if the same behaviour happens on Linux as well, as macOS is Unix-based.
